WIP

diff --git a/.github/workflows/build_nightly.yml b/.github/workflows/build_nightly.yml
--- a/.github/workflows/build_nightly.yml
+++ b/.github/workflows/build_nightly.yml
@@ -16,7 +16,7 @@ jobs:
       matrix:
         isam:
           - db
-          - visam
+#          - visam
 
     steps:
 
@@ -113,12 +113,12 @@ jobs:
       # Note2: gnucobol-VERSION removed on success
       - name: Build distribution archive & run tests
         run: |
-          make -C _build distcheck --jobs=$(($(nproc)+1))           \
-                         TESTSUITEFLAGS="--jobs=$(($(nproc)+1))" || \
-          make -C _build/gnucobol-$VERSION/_build/sub/tests check   \
-                         TESTSUITEFLAGS="--recheck --verbose"
+          # make -C _build distcheck --jobs=$(($(nproc)+1))           \
+          #                TESTSUITEFLAGS="--jobs=$(($(nproc)+1))" || \
+          # make -C _build/gnucobol-$VERSION/_build/sub/tests check   \
+          #                TESTSUITEFLAGS="--recheck --verbose"
           make -C _build --jobs=$(($(nproc)+1)) dist DIST_TARGETS="dist-gzip distwin-zip"
-          make -C _build --jobs=$(($(nproc)+1)) distbin DISTBIN_TARGETS="distbin-xz"
+          # make -C _build --jobs=$(($(nproc)+1)) distbin DISTBIN_TARGETS="distbin-xz"
 
       - name: Upload testsuite.log
         if: ${{ !cancelled() }}
@@ -136,47 +136,48 @@ jobs:
           if-no-files-found: error
           retention-days: 0
 
-      - name: Upload dist tarball (Windows)
-        if: ${{ matrix.isam != 'visam' }}
-        uses: actions/upload-artifact@v7
-        with:
-          name: gnucobol-ci windows source distribution
-          path: _build/gnucobol*.zip
-          if-no-files-found: error
-          retention-days: 0
+      # - name: Upload dist tarball (Windows)
+      #   if: ${{ matrix.isam != 'visam' }}
+      #   uses: actions/upload-artifact@v7
+      #   with:
+      #     name: gnucobol-ci windows source distribution
+      #     path: _build/gnucobol*.zip
+      #     if-no-files-found: error
+      #     retention-days: 0
 
-      - name: Upload test binaries
-        if: ${{ matrix.isam != 'visam' }}
-        uses: actions/upload-artifact@v7
-        with:
-          name: gnucobol-ci binary distribution
-          path: _build/gnucobol*.tar.xz
-          if-no-files-found: error
-          retention-days: 0
+      # - name: Upload test binaries
+      #   if: ${{ matrix.isam != 'visam' }}
+      #   uses: actions/upload-artifact@v7
+      #   with:
+      #     name: gnucobol-ci binary distribution
+      #     path: _build/gnucobol*.tar.xz
+      #     if-no-files-found: error
+      #     retention-days: 0
 
-      - name: Cache newcob.val
-        uses: actions/cache@v6
-        with:
-          path: _build/tests/cobol85/newcob.val
-          key: newcob-val
-          enableCrossOsArchive: true
+      # - name: Cache newcob.val
+      #   uses: actions/cache@v6
+      #   with:
+      #     path: _build/tests/cobol85/newcob.val
+      #     key: newcob-val
+      #     enableCrossOsArchive: true
 
-      - name: Run NIST85 testsuite
-        run: make -C _build test --jobs=$(($(nproc)+1))
+      # - name: Run NIST85 testsuite
+      #   run: make -C _build test --jobs=$(($(nproc)+1))
 
-      - name: Upload NIST85 Test Suite results
-        if: ${{ !cancelled() }}
-        uses: actions/upload-artifact@v7
-        with:
-          name: NIST85 results on ${{ github.job }}-${{ matrix.isam }}
-          path: |
-            _build/tests/cobol85/summary.*
-            _build/tests/cobol85/**/*.log
-            _build/tests/cobol85/**/*.out
-            _build/tests/cobol85/**/duration.txt
+      # - name: Upload NIST85 Test Suite results
+      #   if: ${{ !cancelled() }}
+      #   uses: actions/upload-artifact@v7
+      #   with:
+      #     name: NIST85 results on ${{ github.job }}-${{ matrix.isam }}
+      #     path: |
+      #       _build/tests/cobol85/summary.*
+      #       _build/tests/cobol85/**/*.log
+      #       _build/tests/cobol85/**/*.out
+      #       _build/tests/cobol85/**/duration.txt
 
 
   build_clang:
+    if: ${{ false }}
     name: Build, test and provide nightly (Clang)
     runs-on: ubuntu-latest
     timeout-minutes: 10   # usually around 5-7 minutes
@@ -315,6 +316,7 @@ jobs:
 
 
   build_32_bit:
+    if: ${{ false }}
     name: Build and test on 32-bit
     needs: build
     runs-on: ubuntu-latest
@@ -404,6 +406,7 @@ jobs:
 
 
   build_minimal:
+    if: ${{ false }}
     name: Build and test with minimal dependencies
     needs: build
     runs-on: ubuntu-latest
@@ -479,6 +482,7 @@ jobs:
 
 
   coverage:
+    if: ${{ false }}
     name: Coverage and Warnings
     needs: build
     runs-on: ubuntu-latest
@@ -840,33 +844,33 @@ jobs:
           rem  Note: the extra CPATH above is only required in debug builds
           rem  (otherwise gcc invoked from cobc does not find libcob.h [pre-inst-env]), for some reason...
 
-      - name: Cache newcob.val
-        uses: actions/cache@v6
-        with:
-          path: _build/tests/cobol85/newcob.val
-          key: newcob-val
-          enableCrossOsArchive: true
+      # - name: Cache newcob.val
+      #   uses: actions/cache@v6
+      #   with:
+      #     path: _build/tests/cobol85/newcob.val
+      #     key: newcob-val
+      #     enableCrossOsArchive: true
 
-      - name: Run NIST85 testsuite
-        # if we ever need to disable something in the tests: skip like here IF106A
-        # and later expect a failure
-        #   perl -pi -e 's/^# OBNC1M/\$skip{IF106A} = 1; # OBNC1M/' tests/cobol85/report.pl
-        #   %MSYS_BASH% -lc "make -C _build test --jobs=$(($(nproc)+1)) CPATH=$(pwd) || echo \"WARNING: NIST85 did not pass!\""
-        run: |
-          %MSYS_BASH% -lc "make -C _build test --jobs=$(($(nproc)+1)) CPATH=$(pwd)"
-          rem  Note: the extra CPATH above is only required in debug builds
-          rem  (otherwise gcc invoked from cobc does not find libcob.h [atlocal]), for some reason...
+      # - name: Run NIST85 testsuite
+      #   # if we ever need to disable something in the tests: skip like here IF106A
+      #   # and later expect a failure
+      #   #   perl -pi -e 's/^# OBNC1M/\$skip{IF106A} = 1; # OBNC1M/' tests/cobol85/report.pl
+      #   #   %MSYS_BASH% -lc "make -C _build test --jobs=$(($(nproc)+1)) CPATH=$(pwd) || echo \"WARNING: NIST85 did not pass!\""
+      #   run: |
+      #     %MSYS_BASH% -lc "make -C _build test --jobs=$(($(nproc)+1)) CPATH=$(pwd)"
+      #     rem  Note: the extra CPATH above is only required in debug builds
+      #     rem  (otherwise gcc invoked from cobc does not find libcob.h [atlocal]), for some reason...
 
-      - name: Upload NIST85 Test Suite results
-        if: ${{ !cancelled() }}
-        uses: actions/upload-artifact@v7
-        with:
-          name: NIST85 results on msys-${{ matrix.target }}
-          path: |
-            _build/tests/cobol85/summary.*
-            _build/tests/cobol85/**/*.log
-            _build/tests/cobol85/**/*.out
-            _build/tests/cobol85/**/duration.txt
+      # - name: Upload NIST85 Test Suite results
+      #   if: ${{ !cancelled() }}
+      #   uses: actions/upload-artifact@v7
+      #   with:
+      #     name: NIST85 results on msys-${{ matrix.target }}
+      #     path: |
+      #       _build/tests/cobol85/summary.*
+      #       _build/tests/cobol85/**/*.log
+      #       _build/tests/cobol85/**/*.out
+      #       _build/tests/cobol85/**/duration.txt
 
       - name: Adjust testsuite
         run: |
@@ -887,7 +891,8 @@ jobs:
         run: |
           rem To work around regular hangs we run NIST first, then the internal
           rem and the later only with 2 jobs -> --jobs does not seem to have any effect in this env
-          %MSYS_BASH% -lc "make -C _build check TESTSUITEFLAGS=\"--jobs=2\" CPATH=$(pwd)"
+          rem %MSYS_BASH% -lc "make -C _build check TESTSUITEFLAGS=\"--jobs=2\" CPATH=$(pwd)"
+          %MSYS_BASH% -lc "make -C _build check TESTSUITEFLAGS=\"--verbose 945\" CPATH=$(pwd)"
           rem  Note: the extra CPATH above is only required in debug builds
           rem  (otherwise gcc invoked from cobc does not find libcob.h [atlocal]), for some reason...
 
